### ISSUE TITLE
[BUG] Missing Node Dependency In Package File

### ISSUE THREAD

**Issue by justliamj** [becurrie/titandash#175]
I've followed all the steps listed in the Dependencies but when I goto run **setup.bat** I get the following error;

_npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself._

**My steps:**

- Downloaded Titandash & unzipped
- Installed Python 3.7 (added to $PATH)
- Opened cmd and ran _pip install virtualenv_ & _pip install virtualenvwrapper-win_
- Installed Node.js
- Installed Tesseract OCR 3.05 (added to $PATH)
- Installed Nox Emulator (including Tap Titans 2)
- Opened Powershell and ran the required command
- Rebooted computer
- Opened Ubuntu and ran the required commands
- Ran setup.bat
- Error

![kx9rrsr](https://user-images.githubusercontent.com/55626009/65387273-ab686580-dd3d-11e9-8bb8-cf16484641ec.png)

**Comment by becurrie** [comment]
Ahh yes I forgot about this one popping up! This shouldn't cause any issues with the web application or bot itself though, are you able to run through the rest of the steps, or does the setup.bat file close after that error happens?

Regardless, I'll add that dependency to the package file for the next release (1.5.3)

**Comment by justliamj** [comment]
Setup.bat closes as the error appears

**Comment by becurrie** [comment]
Interesting.. I'll push this fix up to 1.5.3 as soon as possible!

**Comment by becurrie** [comment]
Resolved by #178
