### ISSUE TITLE
[BUG] Updating Configuration/Saving error

### ISSUE THREAD

**Issue by ChikyuTenshi** [becurrie/titandash#296]
**Describe the bug**
Updating Configuration/Saving shoots back an error

**To Reproduce**
1. Go to 'Configuration Tab'
2. Trying saving your Configuration (with and without changing anything)
3. Receive the "Some errors are present on the configuration, please fix them before saving." error

**Expected Behavior**
Configuration file saves properly

**Comment by becurrie** [comment]
I'm unable to replicate this locally. Does this happen when you edit one of your existing configurations only?

**Comment by becurrie** [comment]
Additionally, could you try importing this configuration, and see if you can edit/save it?

> 0:PUSHER&1:+BT&2:+BF&3:0&4:0&5:memu&6:+BT&7:+BT&9:+BT&79:+BT&80:+BT&8:+BT&10:+BT&74:+BT&75:+BT&76:+BT&77:+BF&78:+BF&11:+BF&12:40&13:180&14:60&15:20&16:+BT&17:+BF&18:1&19:+BT&20:+BF&21:1&22:+BF&23:+BF&24:30&34:+BT&81:60&92:+BT&70:+BT&35:5&36:+BT&82:45&93:+BT&37:2&83:+BT&84:60&94:+BT&85:disable&86:max&87:max&88:max&89:max&90:max&91:+BT&95:60&39:+BT&40:0&41:30&42:30&43:30&44:30&45:40&49:+BT&71:+BT&72:2&73:8&50:45&51:0&52:+BF&53:0.000&55:+BT&54:+BT&57:+BT&60:+BT&61:+BF&62:60&63:+BT&64:+BF&65:300&66:5&67:45&68:+BT&69:INFO&56:+MS&58:+MNone&59:+M95|20|94|35|32|33|34

**Comment by ChikyuTenshi** [comment]
Editing existing configuration and creating a new configuration, even imported results in an error

**Comment by becurrie** [comment]
This is definitely weird... Could you send me your `titan.sqlite3` database? It must be some sort of issue with that, or at least, that's the only think I can think of right now.

**Comment by becurrie** [comment]
We've determined that this most likely a cachine issue. Chikyu is able to fix it by using chrome and clearing the cache, their main browser was using the old javascript and was fixed when they used an incognito window.

I'm going to make an issue for cache busting within titandash for this.
