### ISSUE TITLE
Improve Minigame Behavior And Add Sleep To Taps

### ISSUE THREAD

**Issue by breezko** [becurrie/titandash#484]
**Is your feature request related to a problem? Please describe.**
When enable minigames not every click is performed.

**Describe the solution you'd like**
Add some timings so the clicks are performed.

**Describe alternatives you've considered**
-
**Additional context**
The Emulator doesn't support many clicks (pyautogui defaults to 100 click/s)

**Comment by skvie** [comment]
unfortunately the ocr changes are in that too...

**Comment by becurrie** [comment]
Resolved by #505
