### ISSUE TITLE
Address 3.9.0 Issues

### ISSUE THREAD

**Issue by ormagoden** [becurrie/titandash#487]
- Fixed/Static Header Bars ✔️ 
- New Artifact Images (Fix Downsizing Here As Well) ✔️
- Tourney Icon Coords Change ✔️
- Skills Max Level Not Working ✔️

**Comment by becurrie** [comment]
Noted, I'm gonna convert this to a generic 3.9 fixes issue.

**Comment by becurrie** [comment]
Resolved by #489
