### ISSUE TITLE
Fix Issues With Goto Panel Functionality

### ISSUE THREAD

**Issue by breezko** [becurrie/titandash#492]
- Master Panel (master.png) sometimes contains a "new" image. This screws up the goto_panel functionality for that panel. Solution here is to make the image smaller, so the "new" badge is irrelevant.

- Heroes Panel sometimes contains some "new" badges, these cause the duplicate image check to fail. Solution here is to modify the region used so that no "new" badges matter.

**Comment by becurrie** [comment]
Sweet, got a fix for this, pushing now.

**Comment by becurrie** [comment]
Resolved by #493

**Comment by becurrie** [comment]
Fix Amended #502
