### ISSUE TITLE
[BUG] Collect milestones reward instead of daily achievements rewards

### ISSUE THREAD

**Issue by ormagoden** [becurrie/titandash#518]
**Describe the bug**
While bot run daily achievements function and milestones reward is ready to collect, when bot open a achievements menu, it will start at "Milestones tab" and then bot collects milestones reward instead of daily achievements rewards

**To Reproduce**
1. Milestones reward is ready to collect
2. Daily Achievement settings -> Enable Daily Achievements is check
3. Milestones settings -> Enable Milestones is uncheck

**Desktop (please complete the following information):**
 - titandash 2.0.4
 - memu 7.0.1

**Comment by breezko** [comment]
@ormagoden Do you have a LOG output you can provide?
Check `titandash\titanbot\titandash\bot\logs`

**Comment by ormagoden** [comment]
I can't find LOG at that moment, but no errors, bot works fine.

**Comment by becurrie** [comment]
I'm unable to replicate this while testing, opening the daily achievements from the master panel always resets the panel to the "daily" tab first, not the "milestones" tab. We can easily add an extra click to make sure "daily" heading is clicked on before collection, but are you able to get a video of the error occurring @ormagoden .

@breezko Does your game also always open on the "daily" tab?

**Comment by breezko** [comment]
@becurrie not replicatable imho.
I've got no issues.

**Comment by becurrie** [comment]
@ormagoden If you can provide a video of this issue occurring, I'll re-open the issue and we can update the daily achievements function to ensure the proper header is open before collecting. I'm closing for the time being.

**Comment by ormagoden** [comment]
@becurrie @breezko Here's a reproduce video, tapped by myself
[https://streamable.com/kno3f8](url)
Tap titans 3.9.2 from https://play.google.com/store/apps?hl=th
