### ISSUE TITLE
Fix Level Heroes Skipping Drag/Click Due To Static Headers

### ISSUE THREAD

**Issue by becurrie** [becurrie/titandash#523]
This was missed during the initial 3.9.0 changes. Currently, if no max heroes are present, we are meant to travel to the bottom of the heroes panel and scroll up and level heroes iteratively. The way this works now is by looping while the "masteries" image isn't present, which worked before because that image was stuck at the top.

That image is now always present, so we only ever level once then leave the level heroes function.

**Comment by becurrie** [comment]
https://drive.google.com/open?id=1jtj8q1hI_WsDzB7S_Dod1I1weHfCMj_y

**Comment by breezko** [comment]
Huge, this annoyed me a while too when switching accounts. 😆

**Comment by becurrie** [comment]
Resolved by #524
