### ISSUE TITLE
Add Threshold To Max Stage Prestige Checks

### ISSUE THREAD

**Issue by fafmau** [becurrie/titandash#543]
Hello and first of all I am sorry for my level of English.
For prestige at max stage, would it not be possible to verify that the maximum stage is reached several times in a row before initializing prestige to avoid character recognition errors?

thx

**Comment by becurrie** [comment]
Yes, this is a pretty good idea and pretty simple to implement, I'll look into it 👍

**Comment by becurrie** [comment]
Resolved by #550
