### ISSUE TITLE
Fix DivisionByZero Error With Maximum Stage (Statistics)

### ISSUE THREAD

**Issue by ivonivon** [becurrie/titandash#556]
ZeroDivisionError at /
float division by zero
Request Method:    GET
Request URL:    http://localhost:10681/
Django Version:    2.2.10
Exception Type:    ZeroDivisionError
Exception Value:
float division by zero
Exception Location:    D:\titandash-2.0.7\titanbot\titandash\models\bot.py in get_diff_from_max_stage, line 165
Python Executable:    C:\Users\zz\Envs\titandash\Scripts\python.exe
Python Version:    3.7.7
Python Path:
['C:\Users\zz\Envs\titandash\lib\site-packages\git\ext\gitdb',
 'D:\titandash-2.0.7\titanbot',
 'C:\Users\zz\Envs\titandash\Scripts\python37.zip',
 'c:\program files\python37\DLLs',
 'c:\program files\python37\lib',
 'c:\program files\python37',
 'C:\Users\zz\Envs\titandash',
 'C:\Users\zz\Envs\titandash\lib\site-packages',
 'C:\Users\zz\Envs\titandash\lib\site-packages\win32',
 'C:\Users\zz\Envs\titandash\lib\site-packages\win32\lib',
 'C:\Users\zz\Envs\titandash\lib\site-packages\Pythonwin',
 'D:\titandash-2.0.7\titanbot',
 'D:\titandash-2.0.7',
 'D:\titandash-2.0.7\titanbot\titandash',
 'C:\Users\zz\Envs\titandash\lib\site-packages\gitdb\ext\smmap']
Server time:    Fri, 29 May 2020 03:07:56 +0000

**Comment by becurrie** [comment]
Resolved by #557
