### ISSUE TITLE
Prestige level not reading properly

### ISSUE THREAD

**Issue by bluishmatt** [becurrie/titandash#571]
Config is set to prestige at level 10250. However, the bot reads 10xxx as 70xxx and frequently prestiges too early. Seems like the OCR? reader isn't accurate. Is there any way to improve this?

Thanks,
Matt

**Comment by becurrie** [comment]
@bluishmatt Unfortunately not at the moment, the stage ocr is inaccurate at lower stages I find, your best bet at the moment is to use the timed prestige functionality wholesale and disable the stage specific stuff right now.

**Comment by becurrie** [comment]
Closing since this is a known bug.
