### ISSUE TITLE
Installation not possible due to missing files

### ISSUE THREAD

**Issue by Xatulu** [becurrie/titandash#79]
Great project, looking really great! 
I wanted to give it a try - but sadly, the package.json file is listed in your gitignore - so the "npm install" command is actually not working.

Also, not too sure, but shouldn't the logs and static file folders not also be included in the Repo?

**Comment by becurrie** [comment]
Thanks for bringing this to my attention, I'll take a look as soon as possible and fix up any directories/files present that should/shouldn't be!

**Comment by becurrie** [comment]
This should be fixed up now in master. Let me know if you run into any other issues!

**Comment by becurrie** [comment]
Resolved by #80
