### ISSUE TITLE
Swap Headgear When Max Hero Type Is Matching Gear Types

### ISSUE THREAD

**Issue by becurrie** [becurrie/titandash#89]
This would be really useful to allow the fastest push times...

Say at stage 45k your max hero is a spell hero, but you had a melee headgear on beforehand, you need to manually swap to your best spell gear piece but this may not be possible...

Some system should be put in place to ensure we can swap to proper gear when needed.

**Comment by becurrie** [comment]
I've come back to this with some new thoughts... And a design that could work.

Basically, it could work like this.

1. Enable/Disable the functionality, no additional configuration should be needed.
2. Potentially use an interval to define how often the check should occur to change the users headgear.
3. During the check, the equipment panel is open, un-collapsed, and the "Headgear" tab is opened.
4. We can use image recognition and a defined region to take photos of each piece of gear available (It should be noted to users that it's much more efficient to just simply only have three pieces of headgear). Although they could obtain some while playing, that should be okay as long as they have three "strong" ones they use for each damage type.
5. Slowly travel down the equipment headgear tab, taking photos and parsing information out of each one, until we reach the end (A duplicate image is taken, similar to the new artifact parsing).
6. Note, as we travel down, we should ignore any images that already exist (since the scrolling may not be completely accurate).
7. We can organize each one into it's own category (Ranged, Melee, Spell).
8. Based on the damage available (1.34eXXX), we can determine which one is the strongest (We should enforce the use of scientific notation as well).
9. We should have some sort of data structure at this point with the strongest available pieces of equipment.

---

The hero check itself should just look at the top of the heroes panel, checking each hero in the list until one with levels is found, and them using image search to find either the melee, spell or ranged identifier.

**Comment by becurrie** [comment]
** Might be easier to let users choose an "index" for each type they want to use, "spell, ranged, melee". This saves the bot needing to perform OCR check (expensive, avoid where possible), as long as the users equipment tab is clean, and/or they have 100 pieces of equipment already, this will not fail at any point.

The one pain point, in my opinion is that when new equipment is received, it may be placed above existing equipment... Which would break the chosen indexes by users.

**Comment by nicknoel251289** [comment]
Just a thought but perhaps you could also use the armor/item lock symbol as the only pieces to work with for headgear. 

It would require users to decide which pieces beforehand.

**Comment by becurrie** [comment]
@nicknoel251289 Great idea, this would _at least_ provide the bot with a mechanism for skipping irrelevant pieces of gear.

**Comment by becurrie** [comment]
Resolved by #440
